name: Setup
description: Setup bun, Node and install packages
inputs:
  package-registry: # id of input
    description: 'PACKAGE_REGISTRY'
    required: false
    default: 'https://registry.npmjs.org/'

runs:
  using: composite
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        registry-url: ${{ inputs.package-registry }}

    - name: Install Dependencies
      shell: bash
      run: bun i
