name: Prepare Release PR

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Capture New Release Version
        run: |
          pnpm changeset status --output=release.json
          echo "NEW_VERSION=$(jq -r '.releases | map(.name+"@"+.newVersion) | join(",")' release.json)" >> "$GITHUB_ENV"
          rm release.json

      - name: Create Release PR if needed
        uses: changesets/action@v1
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
