name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          package-registry: 'https://registry.npmjs.org/'

      - name: Capture New Release Version
        run: |
          pnpm changeset status --output=release.json
          echo "NEW_VERSION=$(jq -r '.releases | map(.name+"@"+.newVersion) | join(",")' release.json)" >> "$GITHUB_ENV"
          rm release.json

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: false
          title: "Release version ${{env.NEW_VERSION}}"
          commit: "Update version ${{env.NEW_VERSION}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: release
    if: ${{ needs.release.outputs.published == 'true' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          package-registry: 'https://registry.npmjs.org/'

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npx changeset publish

  publish-github:
    needs: release
    if: ${{ needs.release.outputs.published == 'true' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          package-registry: 'https://npm.pkg.github.com/'

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_PUBLISH_TOKEN }}
        run: npx changeset publish
