name: Publish Release

on:
  push:
    branches: [main]

jobs:
  check-release-commit:
    runs-on: ubuntu-latest
    outputs:
      isRelease: ${{ steps.check.outputs.isRelease }}

    steps:
      - uses: actions/checkout@v4

      - id: check
        run: |
          if git log -1 --pretty=%B | grep -q "Version Packages"; then
            echo "isRelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "isRelease=false" >> "$GITHUB_OUTPUT"
          fi

  publish-npm:
    needs: check-release-commit
    if: needs.check-release-commit.outputs.isRelease == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          package-registry: 'https://registry.npmjs.org/'

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npx changeset publish

  publish-github:
    needs: check-release-commit
    if: needs.check-release-commit.outputs.isRelease == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          package-registry: 'https://npm.pkg.github.com/'

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_PUBLISH_TOKEN }}
        run: npx changeset publish
